### ISSUE TITLE
[master] TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Uranium#128]
Appears for me in 2.1 and master branch.

```
2016-04-20 21:21:03,934 - DEBUG - Autosaving preferences, instances and profiles
2016-04-20 21:21:07,499 - WARNING - Had to convert 'num_faces' with int(): 13550.0 -> 13550 
2016-04-20 21:21:09,032 - DEBUG - Calculating normals took 0.006642341613769531 seconds
2016-04-20 21:21:09,032 - DEBUG - Loaded a mesh with 40650 vertices
2016-04-20 21:21:09,116 - DEBUG - Loading mesh took 1.948810338973999 seconds
2016-04-20 21:21:09,575 - ERROR - Exception: Job <cura.ConvexHullJob.ConvexHullJob object at 0x7f97e40d4f98> caused an exception
2016-04-20 21:21:09,576 - ERROR - Traceback (most recent call last):
2016-04-20 21:21:09,576 - ERROR -   File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 119, in run
2016-04-20 21:21:09,576 - ERROR -     job.run()
2016-04-20 21:21:09,576 - ERROR -   File "/usr/lib/python3/dist-packages/cura/ConvexHullJob.py", line 78, in run
2016-04-20 21:21:09,577 - ERROR -     min_head_hull = hull.getMinkowskiHull(head_and_fans)
2016-04-20 21:21:09,577 - ERROR -   File "/usr/lib/python3/dist-packages/UM/Math/Polygon.py", line 318, in getMinkowskiHull
2016-04-20 21:21:09,577 - ERROR -     sum = self.getMinkowskiSum(other)
2016-04-20 21:21:09,577 - ERROR -   File "/usr/lib/python3/dist-packages/UM/Math/Polygon.py", line 301, in getMinkowskiSum
2016-04-20 21:21:09,577 - ERROR -     points = numpy.zeros((len(self._points) * len(other._points), 2))
2016-04-20 21:21:09,577 - ERROR - TypeError: object of type 'NoneType' has no len()
2016-04-20 21:21:09,850 - DEBUG - Attempting to kill the engine process
2016-04-20 21:21:09,850 - DEBUG - Killing engine process
2016-04-20 21:21:09,852 - DEBUG - Engine process is killed. Received return code -15
2016-04-20 21:21:10,487 - INFO - Backend crashed or closed. Restarting...
2016-04-20 21:21:10,590 - DEBUG - Attempting to kill the engine process
2016-04-20 21:21:10,610 - INFO - Started engine process: /usr/bin/CuraEngine
2016-04-20 21:21:10,617 - DEBUG - Backend connected on port 49674
2016-04-20 21:21:11,095 - WARNING - No objects suitable for one at a time found, or no correct order found
2016-04-20 21:21:18,934 - DEBUG - Autosaving preferences, instances and profiles
```

**Comment by Ghostkeeper** [comment]
Looks like one of the `_points` became None. For the Convex Hull calculation, that usually means that the problem is somewhere else, in my experience, since the Convex Hull calculation is the first thing it does after changing the scene.

**Comment by thopiekar** [comment]
It always happens when opening a stl file. I retried by choosing "Ultimaker 2" as printer and there it works. Additionally I had "Print one by one" enabled. Remember that I enabled this because of a bug I found here. However, it seems to be related to the machine settings (?).

Made the following modification:
```
diff --git a/cura/ConvexHullJob.py b/cura/ConvexHullJob.py
index 9fb1898..ed06e89 100644
--- a/cura/ConvexHullJob.py
+++ b/cura/ConvexHullJob.py
@@ -64,7 +64,9 @@ class ConvexHullJob(Job):
             if profile.getSettingValue("print_sequence") == "one_at_a_time" and not self._node.getParent().callDecoration("isGroup"):
                 # Printing one at a time and it's not an object in a group
                 self._node.callDecoration("setConvexHullBoundary", copy.deepcopy(hull))
+                print("machine_head_with_fans_polygon = %s" %profile.getSettingValue("machine_head_with_fans_polygon"))         
                 head_and_fans = Polygon(numpy.array(profile.getSettingValue("machine_head_with_fans_polygon"), numpy.float32))  
+                print("(1) head_and_fans._points = %s" %repr(head_and_fans._points))                                            
                                                                                                                                 
                 # Full head hull is used to actually check the order.                                                           
                 full_head_hull = hull.getMinkowskiHull(head_and_fans)                                                           
@@ -75,9 +77,13 @@ class ConvexHullJob(Job):                                                                                     
                 head_and_fans = head_and_fans.intersectionConvexHulls(mirrored)                                                 
                                                                                                                                 
                 # Min head hull is used for the push free                                                                       
-                min_head_hull = hull.getMinkowskiHull(head_and_fans)                                                            
-                self._node.callDecoration("setConvexHullHead", min_head_hull)                                                   
-                hull = hull.getMinkowskiHull(Polygon(numpy.array(profile.getSettingValue("machine_head_polygon"),numpy.float32)))
+                print("(2) head_and_fans._points = %s" %repr(head_and_fans._points))                                            
+                if head_and_fans._points:                                                                                       
+                    min_head_hull = hull.getMinkowskiHull(head_and_fans)                                                        
+                    self._node.callDecoration("setConvexHullHead", min_head_hull)                                               
+                    hull = hull.getMinkowskiHull(Polygon(numpy.array(profile.getSettingValue("machine_head_polygon"),numpy.float32)))
+                else:                                                                                                           
+                    self._node.callDecoration("setConvexHullHead", None)                                                        
             else:                                                                                                               
                 self._node.callDecoration("setConvexHullHead", None)                                                            
         if self._node.getParent() is None:  # Node was already deleted before job is done.
```

```
machine_head_with_fans_polygon = [[-20, 10], [10, 10], [10, -10], [-20, -10]]
(1) head_and_fans._points = array([[-20.,  10.],
       [ 10.,  10.],
       [ 10., -10.],
       [-20., -10.]], dtype=float32)
(2) head_and_fans._points = None
```
And got it working now by skipping that part if _points is None. But I don't know whether this is the wanted behavior. Additionally I looked through Polygon.py and found that intersectionConvexHulls(XY) returns an empty Polygon() with _points = None, which is set as default in __init__(). 

Actually I don't see a reason why it fails here :confused:

**Comment by thopiekar** [comment]
I additionally checked the order of the points, which are set in the json files.

In the ultimaker2.json it seems that they are mixed because of simple copy-pasting.
![img_20160422_163032](https://cloud.githubusercontent.com/assets/1847437/14744741/55ea5f18-08a8-11e6-8a83-dd793139abf4.jpg)

Applying the same order in fdmprinter.json makes no difference. So this is not the reason for that issue here.

**Comment by Ghostkeeper** [comment]
Polygons are typically ordered in positive orientation, i.e. counterclockwise. It shouldn't matter here because I believe the convex hull calculation itself computes also the convex hull of the head_and_fans polygon (which might be superfluous actually if we define the machines correctly).

**Comment by Ghostkeeper** [comment]
Problem seems to occur only with very simple models. In more complex models it often misses a few corners.
