### ISSUE TITLE
Run Cura2.5 from Source code get a  Error. 

### ISSUE THREAD

**Issue by ShenRen** [Ultimaker/Uranium#250]
#   All the Source code  , I download form Ultimaker`repository , in Branch 2.5

- src-Cura-2.5.zip 
- src-cura-binary-data-2.5.zip
- src-cura-build-2.5.0.zip
- src-CuraEngine-2.5.zip
- src-fdm_materials-2.5.0.zip
- src-libArcus-2.5.0.zip
- src-libSavitar-2.5.zip
- src-protobuf-stable-3.4.zip
- src-Uranium-2.5.zip

#  Computer`s  is  windows 10 64bit , The required tools are installed.

- git 2.11 64
- cmake 3.7.1 64
- python 3.5.3 _64
- mingw 530_64

## Dependencies (pip list ):

- astroid (1.5.2)
- colorama (0.3.9)
- cx-Freeze (5.0.1)
- enum-compat (0.0.2)
- isort (4.2.5)
- lazy-object-proxy (1.3.1)
- mccabe (0.6.1)
- netifaces (0.10.5)
- nine (1.0.0)
- numpy (1.12.1+mkl)
- numpy-stl (2.2.3)
- pip (9.0.1)
- protobuf (3.0.0)
- py (1.4.33)
- pylint (1.7.1)
- PyQt5 (5.8.2)
- pyserial (3.3)
- pytest (3.0.7)
- python-utils (2.1.0)
- QScintilla (2.10)
- scipy (0.19.0)
- setuptools (28.8.0)
- sip (4.19.2)
- six (1.10.0)
- wrapt (1.10.10)
- zeroconf (0.17.6)

      I have Compiled CuraEngine  and protobuf-3.0.0(both C++ and py) libArcus-2.5.0 . 
So the CuraEngine works well on cmd shell. 

     Further development ,I used the pyqt recommended IDE , Eric6 . 
Mix the rest of the source file , I get project of Cura 2.5 . and this project  can run , So far,  things are all normal . I  can work with cura  2.3.1/ cura 2.4 In the same way.
But on cura 2.5  One problem blocks the slicing process --- Cura can not run curaEngine  backstage.**

## error log is here "
```
2017-05-17 17:35:57,105 - INFO - CuraEngineBackend.CuraEngineBackend.__init__ [64]: Found CuraEngine at: CuraEngine.exe
2017-05-17 17:36:01,855 - INFO - UM.Qt.QtApplication.__init__ [107]: Command line arguments: {'single_instance': False, 'qmljsdebugger': None, 'file': [], 'disable-textures': False, 'external-backend': False}
2017-05-17 17:36:02,043 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:   File "E:\PyQtWorkSpace\Cura_rs_2.5\cura\CuraApplication.py", line 653, in event
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:     return super().event(event)
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:   File "E:\PyQtWorkSpace\Cura_rs_2.5\UM\Qt\QtApplication.py", line 216, in event
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:     event._function_event.call()
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:   File "E:\PyQtWorkSpace\Cura_rs_2.5\UM\Event.py", line 187, in call
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:     self._function(*self._args, **self._kwargs)
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:   File "E:\PyQtWorkSpace\Cura_rs_2.5\UM\..\plugins\CuraEngineBackend\CuraEngineBackend.py", line 479, in _createSocket
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:     super()._createSocket(os.path.abspath(os.path.join(PluginRegistry.getInstance().getPluginPath(self.getPluginId()), "Cura.proto")))
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:   File "E:\PyQtWorkSpace\Cura_rs_2.5\UM\Backend\Backend.py", line 230, in _createSocket
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]:     if not self._socket.registerAllMessageTypes(protocol_file):
2017-05-17 17:36:02,090 - CRITICAL - cura.CrashHandler.show [39]: TypeError: Socket.registerAllMessageTypes(): argument 1 has unexpected type 'str'
```

# I hope someone can help me with this problem ; I don't know Python very well ,!

**Comment by Ghostkeeper** [comment]
I think something went wrong with SIP. `Socket.registerAllMessageTypes()` does expect a `str`.

Could you re-install SIP, and make sure not to just install the Python package but also the actual system library?

**Comment by ShenRen** [comment]
yes, yes, yes ! thank you !
the SIP is not incomplete. I re-install SIP ,and the problem is solved .
