### ISSUE TITLE
Ubntu15.04: Install directory may into /usr/lib/python3/dist-packages

### ISSUE THREAD

**Issue by supergis** [Ultimaker/Uranium#60]
On Ubuntu15.04,make and run:
python3 cura_app.py
got errors: 
```
No module named 'UM'
QWidget: Must construct a QApplication before a QWidget
```
Check the Uranim directory, in the  "/usr/local/lib/python3/dist-packages".but this is NOT default for python.
Install directory may into "/usr/lib/python3/dist-packages" by default.
Then set PYTHONPATH=/usr/local/lib/python3/dist-packages,can start.
Now,got another error as follow:
```
Version: master
Platform: Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
    app.run()
  File "/home/supermap/dev/Cura/cura/CuraApplication.py", line 169, in run
    self.getStorageDevice("LocalFileStorage").removableDrivesChanged.connect(self._removableDrivesChanged)
AttributeError: 'CuraApplication' object has no attribute 'getStorageDevice'
```

**Comment by supergis** [comment]
set cmake prefix as -DCMAKE_INSTALL_PREFIX=/usr, as follow:
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_SITE_PACKAGES_DIR=/usr/lib/python3.4/dist-packages -DURANIUM_PLUGINS_DIR=/usr/lib/python3.4/dist-packages
```
now, make install success.
